[Variables]
IconSize=153
hideconfigbar=1

; Thunderstorms
0=[\xF01E]
; Windy Rain
1=[\xF018]
; Windy Rain
2=[\xF018]
; Thunderstorms
3=[\xF01E]
; T-Storms
4=[\xF01E]
; Rain Snow
5=[\xF017]
; Rain Sleet
6=[\xF017]
; Snow/Rain Icy Mix
7=[\xF017]
; Freezing Drizzle
8=[\xF015]
; Drizzle
9=[\xF01C]
; Freezing Rain
10=[\xF015]
; T-Showers
11=[\xF01D]
; Showers
11=[\xF019]
; Light Rain
11=[\xF019]
; Heavy Rain
12=[\xF019]
; Snow Flurries
13=[\xF076]
; Light Snow
14=[\xF076]
; Snowflakes
15=[\xF076]
; Heavy Snow
16=[\xF076]
; Thunderstorms
17=[\xF01E]
; Hail
18=[\xF015]
; Dust
19=[\xF063]
; Fog
20=[\xF014]
; Haze
21=[\xF0B6]
; Smoke
22=[\xF062]
; Windy
23=[\xF021]
; Windy
24=[\xF021]
; Frigid
25=[\xF076]
; Cloudy
26=[\xF041] 
; Mostly Cloudy Night (the "Night" will not be included)
27=[\xF086]
; Mostly Cloudy
28=[\xF013]
; Partly Cloudy Night (the "Night" will not be included)
29=[\xF086]
; Partly Cloudy
30=[\xF002]
; Clear Night (the "Night" will not be included)
31=[\xF077]
; Sunny
32=[\xF00D]
; Fair
33=[\xF041]
; Mostly Clear Night (the "Night" will not be included)
33=[\xF02E]
; Fair
34=[\xF041]
; Mostly Sunny
34=[\xF002]
; Thunderstorms
35=[\xF01E]
; Hot
36=[\xF072]
; Isolated Thunder
37=[\xF016]
; Scattered T-Storms
38=[\xF01D]
; Scattered Rain
39=[\xF01C]
; Heavy Rain
40=[\xF019]
; Scattered Snow
41=[\xF01B]
; Heavy Snow
42=[\xF01B]
; Windy/Snowy
43=[\xF064]
; Partly Cloudy Day
44=[\xF002]
; Scattered Showers Night (the "Night" will not be included)
45=[\xF03A]
; Snowy Night
46=[\xF038]
; Scattered T-Storms Night (the "Night" will not be included)
47=[\xF02D]
