[Variables]
console=-4
game=523

[mConName]
measure=String
dynamicVariables=1
updateDivider=-1
group=StringMeasures

[mItemIcon1]
measure=String
dynamicVariables=1
updateDivider=-1
group=StringMeasures

[MeasureConfigName]
Measure=String
String=Games
dynamicVariables=1
updateDivider=-1

[mSubConfigName]
Measure=String
String="Menu"
dynamicVariables=1
updateDivider=-1

[parseNpose]
Measure=Script
ScriptFile="#@##CurrentConfig#\#Service#\ParseAndPose.lua"
dynamicVariables=1
updateDivider=-1
