;;Volume knob styles
[WidthHeight]
x=0
y=0
h=#IconSize#
w=#IconSize#
DynamicVariables=1
;;;;;;;;;;;;;;;;;;;;;;
;;BG;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;
[SpinalTapStyleBG]
imagename="#@#images\Volume\SpinalTapBG.png"

[NeonStyleBG]
imagename="#@#images\Volume\MinBG.png"

;;;;;;;;;;;;;;;;;;;;;;
;;Knob;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;
[SpinalTapStyleKnob]
imagename="#@#images\Volume\Vknob.png"

[NeonStyleKnob]
imagename="#@#images\Volume\VneonKnob.png"

;;;;;;;;;;;;;;;;;;;;;;
;;Glare;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;
[SpinalTapStyleGlare]
hidden=0

[NeonStyleGlare]
hidden=1
