[variables]
useBoxArt=1
page=1
BgAlpha=216
scrollPlane=1
sort=size
revOrder=0
filter=none
hiddenList=1014748|
; path 2 origin.exe (this detected autmatically via windows registry)
OriginPath="C:\Program Files (x86)\Origin\Origin.exe"
; specify up to a max of 4 install directories that Origin installs games to
OriginDir1="C:\Program Files (x86)\Origin Games"
OriginDir2=""
OriginDir3=""
OriginDir4=""
