
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;Measures~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[mItemRunLink1]
measure=String
dynamicVariables=1
updateDivider=-1
group=InfoMeasures

[mItemName1]
measure=String
dynamicVariables=1
updateDivider=-1
group=InfoMeasures

[mItemDIR1]
measure=String
dynamicVariables=1
updateDivider=-1
group=InfoMeasures

[mItemId1]
measure=string
dynamicVariables=1
group=InfoMeasures

[mItemDescript1]
measure=String
dynamicVariables=1
updateDivider=-1
group=InfoMeasures


[mItemSize1]
Measure=calc
formula=0
dynamicVariables=1
updateDivider=-1
group=InfoMeasures
ifConditionMode=1
ifcondition=#CurrentSection# > 1073741824
iftrueaction=!setvariable Sizecalc1 "/1073741824,2]#CRLF#GB"
iffalseaction=!setvariable Sizecalc1 "/1048576,1]#CRLF#MB"

[mItemRunLink2]
measure=String
dynamicVariables=1
updateDivider=-1
group=InfoMeasures

[mItemName2]
measure=String
dynamicVariables=1
updateDivider=-1
group=InfoMeasures

[mItemDIR2]
measure=String
dynamicVariables=1
updateDivider=-1
group=InfoMeasures

[mItemId2]
measure=string
dynamicVariables=1
group=InfoMeasures

[mItemDescript2]
measure=String
dynamicVariables=1
updateDivider=-1
group=InfoMeasures


[mItemSize2]
Measure=calc
formula=0
dynamicVariables=1
updateDivider=-1
group=InfoMeasures
ifConditionMode=1
ifcondition=#CurrentSection# > 1073741824
iftrueaction=!setvariable Sizecalc2 "/1073741824,2]#CRLF#GB"
iffalseaction=!setvariable Sizecalc2 "/1048576,1]#CRLF#MB"

[mItemRunLink3]
measure=String
dynamicVariables=1
updateDivider=-1
group=InfoMeasures

[mItemName3]
measure=String
dynamicVariables=1
updateDivider=-1
group=InfoMeasures

[mItemDIR3]
measure=String
dynamicVariables=1
updateDivider=-1
group=InfoMeasures

[mItemId3]
measure=string
dynamicVariables=1
group=InfoMeasures

[mItemDescript3]
measure=String
dynamicVariables=1
updateDivider=-1
group=InfoMeasures


[mItemSize3]
Measure=calc
formula=0
dynamicVariables=1
updateDivider=-1
group=InfoMeasures
ifConditionMode=1
ifcondition=#CurrentSection# > 1073741824
iftrueaction=!setvariable Sizecalc3 "/1073741824,2]#CRLF#GB"
iffalseaction=!setvariable Sizecalc3 "/1048576,1]#CRLF#MB"

[mItemRunLink4]
measure=String
dynamicVariables=1
updateDivider=-1
group=InfoMeasures

[mItemName4]
measure=String
dynamicVariables=1
updateDivider=-1
group=InfoMeasures

[mItemDIR4]
measure=String
dynamicVariables=1
updateDivider=-1
group=InfoMeasures

[mItemId4]
measure=string
dynamicVariables=1
group=InfoMeasures

[mItemDescript4]
measure=String
dynamicVariables=1
updateDivider=-1
group=InfoMeasures


[mItemSize4]
Measure=calc
formula=0
dynamicVariables=1
updateDivider=-1
group=InfoMeasures
ifConditionMode=1
ifcondition=#CurrentSection# > 1073741824
iftrueaction=!setvariable Sizecalc4 "/1073741824,2]#CRLF#GB"
iffalseaction=!setvariable Sizecalc4 "/1048576,1]#CRLF#MB"

[mItemRunLink5]
measure=String
dynamicVariables=1
updateDivider=-1
group=InfoMeasures

[mItemName5]
measure=String
dynamicVariables=1
updateDivider=-1
group=InfoMeasures

[mItemDIR5]
measure=String
dynamicVariables=1
updateDivider=-1
group=InfoMeasures

[mItemId5]
measure=string
dynamicVariables=1
group=InfoMeasures

[mItemDescript5]
measure=String
dynamicVariables=1
updateDivider=-1
group=InfoMeasures


[mItemSize5]
Measure=calc
formula=0
dynamicVariables=1
updateDivider=-1
group=InfoMeasures
ifConditionMode=1
ifcondition=#CurrentSection# > 1073741824
iftrueaction=!setvariable Sizecalc5 "/1073741824,2]#CRLF#GB"
iffalseaction=!setvariable Sizecalc5 "/1048576,1]#CRLF#MB"

[mItemRunLink6]
measure=String
dynamicVariables=1
updateDivider=-1
group=InfoMeasures

[mItemName6]
measure=String
dynamicVariables=1
updateDivider=-1
group=InfoMeasures

[mItemDIR6]
measure=String
dynamicVariables=1
updateDivider=-1
group=InfoMeasures

[mItemId6]
measure=string
dynamicVariables=1
group=InfoMeasures

[mItemDescript6]
measure=String
dynamicVariables=1
updateDivider=-1
group=InfoMeasures


[mItemSize6]
Measure=calc
formula=0
dynamicVariables=1
updateDivider=-1
group=InfoMeasures
ifConditionMode=1
ifcondition=#CurrentSection# > 1073741824
iftrueaction=!setvariable Sizecalc6 "/1073741824,2]#CRLF#GB"
iffalseaction=!setvariable Sizecalc6 "/1048576,1]#CRLF#MB"

[mItemRunLink7]
measure=String
dynamicVariables=1
updateDivider=-1
group=InfoMeasures

[mItemName7]
measure=String
dynamicVariables=1
updateDivider=-1
group=InfoMeasures

[mItemDIR7]
measure=String
dynamicVariables=1
updateDivider=-1
group=InfoMeasures

[mItemId7]
measure=string
dynamicVariables=1
group=InfoMeasures

[mItemDescript7]
measure=String
dynamicVariables=1
updateDivider=-1
group=InfoMeasures


[mItemSize7]
Measure=calc
formula=0
dynamicVariables=1
updateDivider=-1
group=InfoMeasures
ifConditionMode=1
ifcondition=#CurrentSection# > 1073741824
iftrueaction=!setvariable Sizecalc7 "/1073741824,2]#CRLF#GB"
iffalseaction=!setvariable Sizecalc7 "/1048576,1]#CRLF#MB"

[mItemRunLink8]
measure=String
dynamicVariables=1
updateDivider=-1
group=InfoMeasures

[mItemName8]
measure=String
dynamicVariables=1
updateDivider=-1
group=InfoMeasures

[mItemDIR8]
measure=String
dynamicVariables=1
updateDivider=-1
group=InfoMeasures

[mItemId8]
measure=string
dynamicVariables=1
group=InfoMeasures

[mItemDescript8]
measure=String
dynamicVariables=1
updateDivider=-1
group=InfoMeasures


[mItemSize8]
Measure=calc
formula=0
dynamicVariables=1
updateDivider=-1
group=InfoMeasures
ifConditionMode=1
ifcondition=#CurrentSection# > 1073741824
iftrueaction=!setvariable Sizecalc8 "/1073741824,2]#CRLF#GB"
iffalseaction=!setvariable Sizecalc8 "/1048576,1]#CRLF#MB"

[mItemRunLink9]
measure=String
dynamicVariables=1
updateDivider=-1
group=InfoMeasures

[mItemName9]
measure=String
dynamicVariables=1
updateDivider=-1
group=InfoMeasures

[mItemDIR9]
measure=String
dynamicVariables=1
updateDivider=-1
group=InfoMeasures

[mItemId9]
measure=string
dynamicVariables=1
group=InfoMeasures

[mItemDescript9]
measure=String
dynamicVariables=1
updateDivider=-1
group=InfoMeasures


[mItemSize9]
Measure=calc
formula=0
dynamicVariables=1
updateDivider=-1
group=InfoMeasures
ifConditionMode=1
ifcondition=#CurrentSection# > 1073741824
iftrueaction=!setvariable Sizecalc9 "/1073741824,2]#CRLF#GB"
iffalseaction=!setvariable Sizecalc9 "/1048576,1]#CRLF#MB"

[mItemRunLink10]
measure=String
dynamicVariables=1
updateDivider=-1
group=InfoMeasures

[mItemName10]
measure=String
dynamicVariables=1
updateDivider=-1
group=InfoMeasures

[mItemDIR10]
measure=String
dynamicVariables=1
updateDivider=-1
group=InfoMeasures

[mItemId10]
measure=string
dynamicVariables=1
group=InfoMeasures

[mItemDescript10]
measure=String
dynamicVariables=1
updateDivider=-1
group=InfoMeasures


[mItemSize10]
Measure=calc
formula=0
dynamicVariables=1
updateDivider=-1
group=InfoMeasures
ifConditionMode=1
ifcondition=#CurrentSection# > 1073741824
iftrueaction=!setvariable Sizecalc10 "/1073741824,2]#CRLF#GB"
iffalseaction=!setvariable Sizecalc10 "/1048576,1]#CRLF#MB"

[mItemRunLink11]
measure=String
dynamicVariables=1
updateDivider=-1
group=InfoMeasures

[mItemName11]
measure=String
dynamicVariables=1
updateDivider=-1
group=InfoMeasures

[mItemDIR11]
measure=String
dynamicVariables=1
updateDivider=-1
group=InfoMeasures

[mItemId11]
measure=string
dynamicVariables=1
group=InfoMeasures

[mItemDescript11]
measure=String
dynamicVariables=1
updateDivider=-1
group=InfoMeasures


[mItemSize11]
Measure=calc
formula=0
dynamicVariables=1
updateDivider=-1
group=InfoMeasures
ifConditionMode=1
ifcondition=#CurrentSection# > 1073741824
iftrueaction=!setvariable Sizecalc11 "/1073741824,2]#CRLF#GB"
iffalseaction=!setvariable Sizecalc11 "/1048576,1]#CRLF#MB"

[mItemRunLink12]
measure=String
dynamicVariables=1
updateDivider=-1
group=InfoMeasures

[mItemName12]
measure=String
dynamicVariables=1
updateDivider=-1
group=InfoMeasures

[mItemDIR12]
measure=String
dynamicVariables=1
updateDivider=-1
group=InfoMeasures

[mItemId12]
measure=string
dynamicVariables=1
group=InfoMeasures

[mItemDescript12]
measure=String
dynamicVariables=1
updateDivider=-1
group=InfoMeasures


[mItemSize12]
Measure=calc
formula=0
dynamicVariables=1
updateDivider=-1
group=InfoMeasures
ifConditionMode=1
ifcondition=#CurrentSection# > 1073741824
iftrueaction=!setvariable Sizecalc12 "/1073741824,2]#CRLF#GB"
iffalseaction=!setvariable Sizecalc12 "/1048576,1]#CRLF#MB"

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;Meters~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[1]
meter=image
MeterStyle=IconBG
x=90
y=74
group=item12 | item11 | item10 | item9 | item8 | item7 | item6 | item5 | item4 | item3 | item2 | item1

[infoBG1]
meter=image
meterStyle=infoBG
group=info1

[itemSize1Icon]
meter=image
meterStyle=sizeStyle
group=info1

[itemSize1]
meter=string
text="[m#CurrentSection#:#sizecalc1#"
MeterStyle=InfoStyle
group=info1

[itemDescript1]
meter=string
MeasureName=m#CurrentSection#
MeterStyle=descriptStyle
group=info1

[2]
meter=image
MeterStyle=IconBG
group=item12 | item11 | item10 | item9 | item8 | item7 | item6 | item5 | item4 | item3 | item2

[infoBG2]
meter=image
meterStyle=infoBG
group=info2

[itemSize2Icon]
meter=image
meterStyle=sizeStyle
group=info2

[itemSize2]
meter=string
text="[mItemSize2:#sizecalc2#"
MeterStyle=InfoStyle
group=info2

[itemDescript2]
meter=string
MeasureName=m#CurrentSection#
MeterStyle=descriptStyle
group=info2

[3]
meter=image
MeterStyle=IconBG
group=item12 | item11 | item10 | item9 | item8 | item7 | item6 | item5 | item4 | item3

[infoBG3]
meter=image
meterStyle=infoBG
group=info3

[itemSize3Icon]
meter=image
meterStyle=sizeStyle
group=info3

[itemSize3]
meter=string
text="[mItemSize3:#sizecalc3#"
MeterStyle=InfoStyle
group=info3

[itemDescript3]
meter=string
MeasureName=m#CurrentSection#
MeterStyle=descriptStyle
group=info3

[4]
meter=image
MeterStyle=IconBG
group=item12 | item11 | item10 | item9 | item8 | item7 | item6 | item5 | item4

[infoBG4]
meter=image
meterStyle=infoBG
group=info4

[itemSize4Icon]
meter=image
meterStyle=sizeStyle
group=info4

[itemSize4]
meter=string
text="[mItemSize4:#sizecalc4#"
MeterStyle=InfoStyle
group=info4

[itemDescript4]
meter=string
MeasureName=m#CurrentSection#
MeterStyle=descriptStyle
group=info4

[5]
meter=image
MeterStyle=IconBG
group=item12 | item11 | item10 | item9 | item8 | item7 | item6 | item5

[infoBG5]
meter=image
meterStyle=infoBG
group=info5

[itemSize5Icon]
meter=image
meterStyle=sizeStyle
group=info5

[itemSize5]
meter=string
text="[mItemSize5:#sizecalc5#"
MeterStyle=InfoStyle
group=info5

[itemDescript5]
meter=string
MeasureName=m#CurrentSection#
MeterStyle=descriptStyle
group=info5

[6]
meter=image
MeterStyle=IconBG
group=item12 | item11 | item10 | item9 | item8 | item7 | item6

[infoBG6]
meter=image
meterStyle=infoBG
group=info6

[itemSize6Icon]
meter=image
meterStyle=sizeStyle
group=info6

[itemSize6]
meter=string
text="[mItemSize6:#sizecalc6#"
MeterStyle=InfoStyle
group=info6

[itemDescript6]
meter=string
MeasureName=m#CurrentSection#
MeterStyle=descriptStyle
group=info6

[7]
meter=image
MeterStyle=IconBG
group=item12 | item11 | item10 | item9 | item8 | item7

[infoBG7]
meter=image
meterStyle=infoBG
group=info7

[itemSize7Icon]
meter=image
meterStyle=sizeStyle
group=info7

[itemSize7]
meter=string
text="[mItemSize7:#sizecalc7#"
MeterStyle=InfoStyle
group=info7

[itemDescript7]
meter=string
MeasureName=m#CurrentSection#
MeterStyle=descriptStyle
group=info7

[8]
meter=image
MeterStyle=IconBG
group=item12 | item11 | item10 | item9 | item8

[infoBG8]
meter=image
meterStyle=infoBG
group=info8

[itemSize8Icon]
meter=image
meterStyle=sizeStyle
group=info8

[itemSize8]
meter=string
text="[mItemSize8:#sizecalc8#"
MeterStyle=InfoStyle
group=info8

[itemDescript8]
meter=string
MeasureName=m#CurrentSection#
MeterStyle=descriptStyle
group=info8

[9]
meter=image
MeterStyle=IconBG
group=item12 | item11 | item10 | item9

[infoBG9]
meter=image
meterStyle=infoBG
group=info9

[itemSize9Icon]
meter=image
meterStyle=sizeStyle
group=info9

[itemSize9]
meter=string
text="[mItemSize9:#sizecalc9#"
MeterStyle=InfoStyle
group=info9

[itemDescript9]
meter=string
MeasureName=m#CurrentSection#
MeterStyle=descriptStyle
group=info9

[10]
meter=image
MeterStyle=IconBG
group=item12 | item11 | item10

[infoBG10]
meter=image
meterStyle=infoBG
group=info10

[itemSize10Icon]
meter=image
meterStyle=sizeStyle
group=info10

[itemSize10]
meter=string
text="[mItemSize10:#sizecalc10#"
MeterStyle=InfoStyle
group=info10

[itemDescript10]
meter=string
MeasureName=m#CurrentSection#
MeterStyle=descriptStyle
group=info10

[11]
meter=image
MeterStyle=IconBG
group=item12 | item11

[infoBG11]
meter=image
meterStyle=infoBG
group=info11

[itemSize11Icon]
meter=image
meterStyle=sizeStyle
group=info11

[itemSize11]
meter=string
text="[mItemSize11:#sizecalc11#"
MeterStyle=InfoStyle
group=info11

[itemDescript11]
meter=string
MeasureName=m#CurrentSection#
MeterStyle=descriptStyle
group=info11

[12]
meter=image
MeterStyle=IconBG
group=item12

[infoBG12]
meter=image
meterStyle=infoBG
group=info12

[itemSize12Icon]
meter=image
meterStyle=sizeStyle
group=info12

[itemSize12]
meter=string
text="[mItemSize12:#sizecalc12#"
MeterStyle=InfoStyle
group=info12

[itemDescript12]
meter=string
MeasureName=m#CurrentSection#
MeterStyle=descriptStyle
group=info12
